# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'email',
            },
        ),
    ]
