# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('campid', models.IntegerField(primary_key=True, serialize=False)),
                ('tag1', models.CharField(blank=True, max_length=100, null=True)),
                ('tag2', models.CharField(blank=True, max_length=100, null=True)),
                ('sent', models.IntegerField(blank=True, null=True)),
                ('delivered', models.IntegerField(blank=True, null=True)),
                ('bounces', models.IntegerField(blank=True, null=True)),
                ('opens', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
